import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def build_html(sections: list[dict]) -> str:
    """Build HTML email body from a list of {source, summary} dicts."""
    section_html = ""
    for section in sections:
        section_html += f"""
        <div style="margin-bottom: 32px;">
          <h2 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 6px;">
            {section['source']}
          </h2>
          <div style="line-height: 1.7; color: #34495e;">
            {_markdown_to_html(section['summary'])}
          </div>
        </div>
        """

    return f"""
    <html>
      <body style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 700px;
                   margin: 0 auto; padding: 24px; background: #f9f9f9;">
        <div style="background: white; border-radius: 8px; padding: 32px;
                    box-shadow: 0 2px 8px rgba(0,0,0,0.08);">
          <h1 style="color: #1a1a2e; margin-top: 0;">📰 Daily Tech News</h1>
          {section_html}
          <p style="color: #aaa; font-size: 12px; margin-top: 32px;">
            Generated by Personal-Daily-News
          </p>
        </div>
      </body>
    </html>
    """


def _markdown_to_html(text: str) -> str:
    """Minimal Markdown → HTML: convert bullet lists and bold."""
    import re
    lines = text.splitlines()
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            item = stripped[2:]
            # convert **bold**
            item = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", item)
            # convert [text](url)
            item = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', item)
            html_lines.append(f"<li>{item}</li>")
        else:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            if stripped:
                stripped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped)
                stripped = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', stripped)
                html_lines.append(f"<p>{stripped}</p>")

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def send(subject: str, sections: list[dict], to: str, from_addr: str, password: str) -> None:
    html_body = build_html(sections)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(from_addr, password)
        server.sendmail(from_addr, to, msg.as_string())
